load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    module_name = "ScreenLib",
    name = "ScreenLib",
    srcs = glob(['**/*.swift', '*.swift']),
    deps = [],
    visibility = ["//visibility:public"]
)